name: LCGoLSpeedrunOverlay

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore Solution
      run: nuget restore LCGoLSpeedrunOverlay.sln
      
    - name: Build Solution
      run: msbuild.exe LCGoLSpeedrunOverlay.sln -t:rebuild /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
 
    - name: Upload LiveSplit Component Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: LiveSplit.LCGoL
        path: LiveSplit.LCGoL\bin\Release
        
    - name: Upload Console App Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: LCGoLOverlayConsoleInjector
        path: LCGoLOverlayInjector\bin\Release
