name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Clean Solution
      run: dotnet clean ./LCGoLSpeedrunOverlay.sln --configuration Release && dotnet nuget locals all --clear
    - name: Ensure nuget.org Source
      uses: fabriciomurta/ensure-nuget-source@v1
      with:
        name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Restore NuGets
      run: nuget restore LCGoLSpeedrunOverlay.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
